# Generated by Django 5.2.17 on 2026-10-04 09:25

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("locations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action", models.CharField(db_index=True, max_length=50)),
                ("object_type", models.CharField(blank=True, max_length=50)),
                ("object_id", models.CharField(blank=True, max_length=50)),
                ("details", models.JSONField(blank=True, default=dict)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Taxpayer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "taxpayer_number",
                    models.CharField(editable=False, max_length=20, unique=True),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("INDIVIDUAL", "Individual"),
                            ("BUSINESS", "Business"),
                            ("ORGANISATION", "Organisation / NGO"),
                        ],
                        default="INDIVIDUAL",
                        max_length=15,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("business_name", models.CharField(blank=True, max_length=200)),
                (
                    "national_id",
                    models.CharField(blank=True, db_index=True, max_length=50),
                ),
                ("phone", models.CharField(blank=True, db_index=True, max_length=30)),
                ("address", models.CharField(blank=True, max_length=255)),
                (
                    "property_number",
                    models.CharField(blank=True, db_index=True, max_length=50),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "village",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="taxpayers",
                        to="locations.village",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="TaxType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=20, unique=True)),
                ("name", models.CharField(max_length=150)),
                (
                    "default_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[("SLSH", "Somaliland Shilling"), ("USD", "US Dollar")],
                        default="SLSH",
                        max_length=4,
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("ONE_OFF", "One-off"),
                            ("DAILY", "Daily"),
                            ("MONTHLY", "Monthly"),
                            ("QUARTERLY", "Quarterly"),
                            ("ANNUAL", "Annual"),
                        ],
                        default="ANNUAL",
                        max_length=10,
                    ),
                ),
                (
                    "max_collector_discount_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Largest discount a collector may give without a supervisor.",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tax_types",
                        to="accounts.department",
                    ),
                ),
            ],
            options={
                "ordering": ["department__name", "name"],
            },
        ),
        migrations.CreateModel(
            name="TaxCollection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "receipt_number",
                    models.CharField(editable=False, max_length=30, unique=True),
                ),
                (
                    "client_uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        help_text="Generated by the device; stops the same payment being saved twice when a phone retries on a bad connection.",
                        unique=True,
                    ),
                ),
                ("payer_name", models.CharField(max_length=200)),
                ("payer_phone", models.CharField(blank=True, max_length=30)),
                ("period_start", models.DateField(blank=True, null=True)),
                ("period_end", models.DateField(blank=True, null=True)),
                (
                    "currency",
                    models.CharField(
                        choices=[("SLSH", "Somaliland Shilling"), ("USD", "US Dollar")],
                        default="SLSH",
                        max_length=4,
                    ),
                ),
                (
                    "tax_amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=14,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "discount_type",
                    models.CharField(
                        choices=[
                            ("NONE", "No discount"),
                            ("PERCENT", "Percentage"),
                            ("FIXED", "Fixed amount"),
                        ],
                        default="NONE",
                        max_length=10,
                    ),
                ),
                (
                    "discount_value",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=14,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("discount_reason", models.CharField(blank=True, max_length=255)),
                (
                    "discount_amount",
                    models.DecimalField(
                        decimal_places=2, default=0, editable=False, max_digits=14
                    ),
                ),
                (
                    "amount_paid",
                    models.DecimalField(
                        decimal_places=2, default=0, editable=False, max_digits=14
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("CASH", "Cash"),
                            ("ZAAD", "ZAAD (Telesom)"),
                            ("EDAHAB", "eDahab (Somtel)"),
                            ("BANK", "Bank transfer"),
                            ("CHEQUE", "Cheque"),
                            ("OTHER", "Other"),
                        ],
                        default="CASH",
                        max_length=10,
                    ),
                ),
                (
                    "transaction_reference",
                    models.CharField(
                        blank=True,
                        help_text="ZAAD / eDahab / bank transaction ID.",
                        max_length=100,
                    ),
                ),
                (
                    "collected_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(-90),
                            django.core.validators.MaxValueValidator(90),
                        ],
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(-180),
                            django.core.validators.MaxValueValidator(180),
                        ],
                    ),
                ),
                (
                    "altitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=7,
                        null=True,
                        verbose_name="Altitude (m)",
                    ),
                ),
                (
                    "gps_accuracy",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=7,
                        null=True,
                        verbose_name="GPS accuracy (m)",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("COMPLETED", "Completed"), ("VOIDED", "Voided")],
                        default="COMPLETED",
                        max_length=10,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("void_reason", models.CharField(blank=True, max_length=255)),
                ("voided_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "collector",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="collections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="collections",
                        to="accounts.department",
                    ),
                ),
                (
                    "village",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="collections",
                        to="locations.village",
                    ),
                ),
                (
                    "voided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="voided_collections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "taxpayer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="collections",
                        to="taxes.taxpayer",
                    ),
                ),
                (
                    "tax_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="collections",
                        to="taxes.taxtype",
                    ),
                ),
            ],
            options={
                "ordering": ["-collected_at"],
                "indexes": [
                    models.Index(
                        fields=["collector", "collected_at"],
                        name="taxes_taxco_collect_b98c4e_idx",
                    ),
                    models.Index(
                        fields=["department", "collected_at"],
                        name="taxes_taxco_departm_aa6219_idx",
                    ),
                    models.Index(
                        fields=["status", "collected_at"],
                        name="taxes_taxco_status_9e14f3_idx",
                    ),
                    models.Index(
                        fields=["village", "collected_at"],
                        name="taxes_taxco_village_68ba4a_idx",
                    ),
                    models.Index(
                        fields=["payment_method", "collected_at"],
                        name="taxes_taxco_payment_360ebd_idx",
                    ),
                ],
            },
        ),
    ]
