# Generated by Django 5.2.17 on 2026-10-04 09:34

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taxes", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DutyShift",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                (
                    "collector",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="shifts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="LocationPing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "recorded_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        decimal_places=6,
                        max_digits=9,
                        validators=[
                            django.core.validators.MinValueValidator(-90),
                            django.core.validators.MaxValueValidator(90),
                        ],
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        decimal_places=6,
                        max_digits=9,
                        validators=[
                            django.core.validators.MinValueValidator(-180),
                            django.core.validators.MaxValueValidator(180),
                        ],
                    ),
                ),
                (
                    "altitude",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=7, null=True
                    ),
                ),
                (
                    "accuracy",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=7, null=True
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("SHIFT_START", "Shift started"),
                            ("TRACKING", "On-duty tracking"),
                            ("PAYMENT", "Payment recorded"),
                            ("SHIFT_END", "Shift ended"),
                        ],
                        default="TRACKING",
                        max_length=12,
                    ),
                ),
                (
                    "collector",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="location_pings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "shift",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pings",
                        to="taxes.dutyshift",
                    ),
                ),
            ],
            options={
                "ordering": ["-recorded_at"],
            },
        ),
        migrations.AddIndex(
            model_name="dutyshift",
            index=models.Index(
                fields=["collector", "started_at"],
                name="taxes_dutys_collect_8c46ac_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="dutyshift",
            constraint=models.UniqueConstraint(
                condition=models.Q(("ended_at__isnull", True)),
                fields=("collector",),
                name="one_open_shift_per_collector",
            ),
        ),
        migrations.AddIndex(
            model_name="locationping",
            index=models.Index(
                fields=["collector", "recorded_at"],
                name="taxes_locat_collect_706fe1_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="locationping",
            index=models.Index(
                fields=["recorded_at"], name="taxes_locat_recorde_a26062_idx"
            ),
        ),
    ]
