# Generated by Django 5.2.17 on 2026-10-04 09:33

from django.db import migrations, models


def managers_to_executives(apps, schema_editor):
    # The old "Revenue manager" role is replaced by Executive director and Treasury.
    apps.get_model("accounts", "User").objects.filter(role="MANAGER").update(role="EXECUTIVE")


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("ADMIN", "System administrator"),
                    ("EXECUTIVE", "Executive director"),
                    ("TREASURY", "Treasury"),
                    ("AUDITOR", "Auditor (read-only)"),
                    ("SUPERVISOR", "Supervisor"),
                    ("COLLECTOR", "Tax collector"),
                ],
                default="COLLECTOR",
                max_length=20,
            ),
        ),
        migrations.RunPython(managers_to_executives, migrations.RunPython.noop),
    ]
